### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by sangyoo91** [stubailo/meteor-highlight.js#1]
When will this be updated?

I have some code highlighters that are not working with this package, but is documented in the API. 

And thank you for wrapping this awesome package. I've been using it alot :)

**Comment by stubailo** [comment]
I just realized that I never documented which version of highlight.js this is wrapping. I actually don't know. I'll update to the newest version ASAP and document which one it is.

I'm curious which feature you were looking for?

**Comment by sangyoo91** [comment]
LESS and DJANGO highlighting from what I have discovered is not included in this package.

And again, I thank you for your commitment!

**Comment by stubailo** [comment]
LESS and Django aren't on the list of 22 "common" languages. Highlight.js with all of the languages included is ~400kb. I feel like I shouldn't include all of those by default, so I need a way for people to specify which languages they want.

**Comment by sangyoo91** [comment]
Maybe you can add a configuration part... Or maybe a different package?

**Comment by sangyoo91** [comment]
is there still a way to do this?

**Comment by stubailo** [comment]
I'm going to think about it today!

**Comment by sangyoo91** [comment]
Thanks!

And I had a question to ask you.

What method are you using this to apply to the template?

I have a app in development that requires live preview when users input markdown.

With other people's highlight packages, the code blocks with flicker once to original then get applied with highlighting which is very ugly.

But your package seems to not have that. It stays highlighted all the time.

I've tried other packages (because I needed to use marked package for sanitizing html).

Or is there a way to use this with `chuangbo:marked`  package?

**Comment by stubailo** [comment]
Here is how the integration with the markdown package works:

https://github.com/stubailo/meteor-highlight.js/blob/master/markdown-integration.js

It's a little hacky, but I'm sure something very similar could work with `changbo:marked`.

**Comment by DavidSichau** [comment]
It would be really nice to get an update, as I am not able to add any new languages.

**Comment by zimme** [comment]
I have this working with `chuangbo:marked`, once I'm done with the work I'm doing I'll submit a PR.

**Comment by sangyoo91** [comment]
@zimme Awesome! We appreciate it :)
