### ISSUE TITLE
Integrate with other Markdown packages for Meteor, for example perak:markdown

### ISSUE THREAD

**Issue by jononomo** [stubailo/meteor-highlight.js#3]
In reference to this thread on forums.meteor.com: https://forums.meteor.com/t/how-can-i-get-github-flavored-markdown-with-syntax-highlighting/7865

I would like syntax highlighting for my github-flavored markdown ;-(

**Comment by stubailo** [comment]
Please file a PR! https://github.com/stubailo/meteor-highlight.js#adding-support-for-other-markdown-packages

@zimme recently added support for `chuangbo:marked`!
