### ISSUE TITLE
Document how to fork the package to configure different languages etc.

### ISSUE THREAD

**Issue by dariuszsikorski** [stubailo/meteor-highlight.js#4]
Hello, plugin does not detect scss code, which is very common language and I'm building documentation based on it. I have created `custom highlight.js` build with added less, stylus and scss.

New `highlight.pack.js` is 11kB bigger than `simple_highlight.js.js` which is not a huge difference :)

I tried to integrate new `custom_highlight` into your meteor plugin, but the `hljs=new function()...` contains compressed code which seem to have something more than pure compressed highlight.js

Thanks for Your work anyway :)

**Comment by stubailo** [comment]
So you made a fork of the package, updated the code, and it didn't work?

Can you point me to your new code?

Thanks!

**Comment by dariuszsikorski** [comment]
I made a fork by "meteor add plugin_name", then tried to modify downloaded package in .meteor folder, but without success, since code inside this package was contained more than pure highlight js code, so I had to include my own highlight.js file instead of using plugin.

**Comment by stubailo** [comment]
Ah. Yeah, you can't do it that way. You need to clone this repository into your app's `packages/` directory since Meteor packages installed from Atmosphere don't include the source code. Perhaps I should include directions on how to fork the package to add different source highlighters.
