### ISSUE TITLE
Have a version of this package that doesn't include CSS styles

### ISSUE THREAD

**Issue by zimme** [stubailo/meteor-highlight.js#7]
Should we really be adding a style file? What if people wanna use a different style? then they'll need to override css rules with the important flag, right?

**Comment by stubailo** [comment]
That's a good point! I guess I wanted it to be a drop-in thing that just works. I would be in favor of splitting this into two packages, a core package and the CSS package.

If we want to maintain the functionality of this package, we could do it like this:
- simple:highlight.js: has compiler and CSS
- simple:highlight.js-base: has just the compiler

If we wanted to be super fancy we could try to split out the markdown integrations also. What do you think?

**Comment by zimme** [comment]
If we're splitting out markdown integration too, then it might be a good opportunity to try and get official meteor packaging into the upstream repo, and then `simple` adds the markdown integration and styling on top of it with, `simple:highlight-markdown` and `simple:highlight-style-github` or something like this.

**Comment by stubailo** [comment]
Oh, that's a great point!

**Comment by stephane-r** [comment]
Any news about this ? :)
