### ISSUE TITLE
Can this work with React Layouts?

### ISSUE THREAD

**Issue by karldanninger** [stubailo/meteor-highlight.js#8]
The readme has examples with markdown wrapped spacebars. Is there a way this can work with React layouts?

**Comment by stubailo** [comment]
This package also includes the regular `hljs` library, documented here: http://highlightjs.readthedocs.org/en/latest/api.html

If you have any ideas how I can have a better integration with React, I'd love to accept a PR, just like I have done for various Spacebars markdown packages.

Probably the best way is to do something with template strings, like below:

``` js
const markdownContent = md`
# Heading

Paragraph
`;

render() {
  return (
    <div>
      {markdownContent}
    </div>
  )
}
```

This would work via this mechanism: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/template_strings#Tagged_template_strings

Actually, this seems like it would be an awesome library independent of Meteor - a Markdown compiler that converts template strings to React DOM.

**Comment by karldanninger** [comment]
Haha! Awesome @stubailo, I may take a stab at this at some point.. Thanks for the info
