### ISSUE TITLE
Allow configuring a highlighting color scheme that isn't GitHub

### ISSUE THREAD

**Issue by adrianmteo** [stubailo/meteor-highlight.js#9]

**Comment by stubailo** [comment]
Unfortunately not - this package is intended as a drop-in for people who don't really need any configuration (we are using it in docs.meteor.com and the tutorials on meteor.com).

I'd suggest forking the package and changing the `css` file from `github.css`.

I'm also open to proposals for how to make the CSS configurable, I guess this could mean exporting a bunch of `less` files and having the app developer import then one they want.

**Comment by ivansglazunov** [comment]
Why not just allows you to transfer some variable `theme`?

**Comment by stubailo** [comment]
Because then the package will have to include all of the css for every possible theme.
